name: Update Ipos
on: 
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: grandfleet/dopysel:python-3.8
      env:
        GOOGLE_SERVICE_CREDS: ${{ secrets.CALENDAR_SERVICE_ACCOUNT }}
        STOCK_API: ${{ secrets.STOCK_API }}
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        CALENDAR_SERVICE_ACCOUNT: ${{ secrets.CALENDAR_SERVICE_ACCOUNT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: pip3 install --upgrade pip && pip3 install -r requirements.txt && pip3 install beautifulsoup4==4.9.1
      - name: Run Main Script 
        run: python3 -m browser.invest_ipos
      - name: Storing Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifacts

